version: '3.8'

services:
   mysql:
      image: mysql:latest
      container_name: mysql
      hostname: asc_mcp
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: task
      ports:
        - "3306:3306"
   redis:
      image: "redis:latest"
      hostname: asc_mcp
      ports:
        - "6379:6379"
   collector:
      build:
        context: ./collector
        dockerfile: Dockerfile
      restart: always
      hostname: asc_mcp
      depends_on:
         - server
      
   server:
      build:
        context: ./server
        dockerfile: Dockerfile
      hostname: asc_mcp
      ports:
        - "8080:8080"
      restart: always
      depends_on:
         - redis
      
